# This docker-compose.yml file shows how Supervisor program(s) are reloaded automatically when file changes detected
# under web root /var/www. There are two environment variables used:
#     1. AUTORELOAD_PROGRAMS: space-separated Supervisor program(s) to be reloaded when file changes detected. e.g.,
#            AUTORELOAD_PROGRAMS: "swoole"       # Autoreload Supervisor program "swoole" only.
#            AUTORELOAD_PROGRAMS: "swoole nginx" # Autoreload Supervisor program "swoole" and "nginx".
#     2. AUTORELOAD_ANY_FILES: Optional. If set to "true", "1", "yes", or "y", reload Supervisor program(s) when any
#        files under the root directory (/var/www in this example) is changed; otherwise, reload only when PHP file(s)
#        are changed.
#
version: "3"

services:
  boilerwork-basic:
    container_name: boilerwork-basic
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 4000:9501
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 0
    volumes:
      - ..:/var/www
    networks:
      - app-network

  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
      # - ./data:/var/lib/postgresql/data
      # - ./data/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - app-network

volumes:
  postgres-data:
    external: false

networks:
  app-network:
